services:
  back-task:
    build: ./infra/backend
    container_name: ste_backend_php
    env_file:
      - .env
    environment:
      - APP_UID=${UID}
      - APP_GID=${GID}
    volumes:
      - ./backend:/var/www/html
    restart: unless-stopped
    networks:
      trello_net:
        aliases:
          - backend-php
      app_net:
        aliases:
          - backend-php

  back-nginx:
    image: nginx:alpine
    container_name: ste_backend_nginx
    volumes:
      - ./backend:/var/www/html:ro
      - ./infra/backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "18080:80"
    depends_on:
      - back-task
    restart: unless-stopped
    networks:
      - app_net

  front-dev:
    build:
      context: ./frontend
      dockerfile: ../infra/frontend/Dockerfile
    container_name: ste_frontend_dev
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:18080/api
    command:
      [
        "sh",
        "-lc",
        "mkdir -p /app/node_modules && pnpm install && pnpm dev --host 0.0.0.0 --port 5173",
      ]
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - app_net

  front-prod:
    build:
      context: ./frontend
      dockerfile: ../infra/frontend/Dockerfile
      target: prod
    container_name: ste_frontend_prod
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=http://localhost:18080/api
    ports:
      - "4173:4173"
    restart: unless-stopped
    networks:
      - app_net

networks:
  trello_net:
    external: true
  app_net:
    driver: bridge
